# Generated by Django 5.0 on 2025-02-10 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('puesto', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='encargados_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_instalacion', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estructuras_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=50)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='trabajos_documentos/')),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='pro6.estructura')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=50)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='planes_mantenimiento_documentos/')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='pro6.encargado')),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='pro6.estructura')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_mantenimiento', to='pro6.trabajo')),
            ],
        ),
    ]
